---
pdf_file_rag_task:
  description: |
    Perform precise information retrieval from the provided PDF document to answer the user's query.
    Follow these steps:
    1. Analyze the question: "{input}"
    2. Identify relevant sections in the PDF using semantic search
    3. Extract exact passages that answer the question
    4. Verify the information against multiple parts of the document
    5. Compose a concise answer with direct PDF references
    
    Special Instructions:
    - Highlight numerical data/statistics when present
    - Note conflicting information if found
    - Include page numbers for key findings
  expected_output: "Provide clear and accurate answer based on the PDF content."
  agent: pdf_rag_agent

pdf_file_summary_task:
  description: |
    Transform extracted PDF information into a professional report with complete sections.
    Follow this structure:
    1. Identify 3-5 core themes from the content
    2. Expand each into detailed subsections
    3. Maintain original factual accuracy
    4. Add logical transitions between sections
    
    Content Requirements:
    - Include data visualization suggestions
    - Note any knowledge gaps
    - Highlight actionable insights
  expected_output: |
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: pdf_summary_agent