retrieve_news_task:
  description: >
    Conduct in-depth research on {topic}, identifying the most significant 
    and up-to-date developments. Ensure all findings are relevant to the 
    current year, 2024.
  expected_output: >
    A curated list of the 10 most reliable and relevant websites providing 
    valuable insights on {topic}.
  agent: retrieve_news

website_scrape_task:
  description: >
    Extract key news and insights from the identified websites, ensuring 
    accuracy and completeness in the collected data.
  expected_output: >
    Structured and comprehensive website data, containing all essential 
    information relevant to {topic}.
  agent: website_scraper

ai_news_write_task:
  description: >
    Transform the gathered information into a well-structured, insightful, 
    and engaging news article in markdown format.
  expected_output: >
    A professionally written news article with clear sections, each covering 
    a main topic in detail. The article should be formatted in markdown 
    (excluding '```').
  agent: ai_news_writer

file_write_task:
  description: >
    Store the finalized news article in an organized manner for future access.
  expected_output: >
    A properly formatted news article, saved as news/{date}_news_article.md, 
    containing all the refined information from previous tasks.
  agent: file_writer
